In [22]:
import pandas as pd

In [23]:
d=pd.read_csv(r"C:\Users\sanjoy\Downloads\csv\iris.csv")

In [24]:
d.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [25]:
import numpy as np
import matplotlib.pyplot as plt
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model

In [26]:
X=d.iloc[:,0:4].values
y=d.iloc[:,4].values

In [27]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y1=encoder.fit_transform(y)
Y=pd.get_dummies(y1).values

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,Y,test_size=.2, random_state=0)

In [29]:
model=Sequential()
model.add(Dense(4,input_shape=(4,), activation='relu'))
model.add(Dense(3,activation='softmax'))

In [30]:
model.compile(optimizer="Adam", loss='categorical_crossentropy')
model.fit(X_train,y_train, batch_size=10, epochs=100)

Epoch 1/100
120/120 [==============================] - 0s 2ms/step - loss: 2.2726
Epoch 2/100
120/120 [==============================] - 0s 187us/step - loss: 2.0971
Epoch 3/100
120/120 [==============================] - 0s 174us/step - loss: 1.9314
Epoch 4/100
120/120 [==============================] - 0s 213us/step - loss: 1.8018
Epoch 5/100
120/120 [==============================] - 0s 229us/step - loss: 1.6740
Epoch 6/100
120/120 [==============================] - 0s 209us/step - loss: 1.5622
Epoch 7/100
120/120 [==============================] - 0s 220us/step - loss: 1.4474
Epoch 8/100
120/120 [==============================] - 0s 185us/step - loss: 1.3385
Epoch 9/100
120/120 [==============================] - 0s 193us/step - loss: 1.2399
Epoch 10/100
120/120 [==============================] - 0s 231us/step - loss: 1.1399
Epoch 11/100
120/120 [==============================] - 0s 251us/step - loss: 1.0508
Epoch 12/100
120/120 [==============================] - 0s 195us/step - loss

120/120 [==============================] - 0s 177us/step - loss: 0.4125
Epoch 98/100
120/120 [==============================] - 0s 214us/step - loss: 0.4101
Epoch 99/100
120/120 [==============================] - 0s 211us/step - loss: 0.4080
Epoch 100/100
120/120 [==============================] - 0s 211us/step - loss: 0.4058


In [31]:
y_pred=model.predict(X_test)
y_test_class=np.argmax(y_test, axis=1)
y_pred_class=np.argmax(y_pred, axis=1)

In [32]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test_class, y_pred_class))
print(confusion_matrix(y_test_class, y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.38      0.56        13
           2       0.43      1.00      0.60         6

    accuracy                           0.73        30
   macro avg       0.81      0.79      0.72        30
weighted avg       0.89      0.73      0.73        30

[[11  0  0]
 [ 0  5  8]
 [ 0  0  6]]
